version = 0.1

[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "TripTrekStack"
resolve_s3 = true
s3_prefix = "TripTrekStack"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
disable_rollback = false
image_repositories = []
parameter_overrides = "ImageUploadBucket=trek-a-trip-images-bucket CognitoUserPoolId=us-east-1_Ks6i9yln5 CognitoUserPoolClientId=3n8imnlps0an3lj9rp2umi7bu6"

[default.build.parameters]
cached = true
parallel = true
use_container = false
